export const FETCH_FIXTURES_SUCCESS        = "FETCH_FIXTURES_SUCCESS";
export const FETCH_FIXTURES_REQUEST        = "FETCH_FIXTURES_REQUEST";

export const FETCH_TODAYS_FIXTURES_SUCCESS = "FETCH_TODAYS_FIXTURES_SUCCESS";
export const FETCH_TODAYS_FIXTURES_REQUEST = "FETCH_TODAYS_FIXTURES_REQUEST";

export const FETCH_STANDINGS_SUCCESS       = "FETCH_STANDINGS_SUCCESS";
export const FETCH_STANDINGS_REQUEST       = "FETCH_STANDINGS_REQUEST";

export const FETCH_TEAMS_SUCCESS           = "FETCH_TEAMS_SUCCESS";
export const FETCH_TEAMS_REQUEST           = "FETCH_TEAMS_REQUEST";

export const FETCH_TEAM_SUCCESS            = "FETCH_TEAM_SUCCESS";
export const FETCH_TEAM_REQUEST            = "FETCH_TEAM_REQUEST";

export const FETCH_PLAYERS_SUCCESS         = "FETCH_PLAYERS_SUCCESS";
export const FETCH_PLAYERS_REQUEST         = "FETCH_PLAYERS_REQUEST";

export const FETCH_COMPETITIONS_SUCCESS    = "FETCH_COMPETITIONS_SUCCESS";
export const FETCH_COMPETITIONS_REQUEST    = "FETCH_COMPETITIONS_REQUEST";

export const FETCH_COMPETITION_SUCCESS     = "FETCH_COMPETITION_SUCCESS";
export const FETCH_COMPETITION_REQUEST     = "FETCH_COMPETITION_REQUEST";

export const FETCH_SEASONS_SUCCESS         = "FETCH_SEASONS_SUCCESS";
export const FETCH_SEASONS_REQUEST         = "FETCH_SEASONS_REQUEST";

export const FETCH_SEASON_SUCCESS          = "FETCH_SEASON_SUCCESS";
export const FETCH_SEASON_REQUEST          = "FETCH_SEASON_REQUEST";

export const NAVIGATE_PAGE                 = "NAVIGATE_PAGE";
export const LOGOUT                        = "LOGOUT";
