export const FETCH_FIXTURES_SUCCESS     = 'FETCH_FIXTURES_SUCCESS';
export const FETCH_TEAMS_SUCCESS        = 'FETCH_TEAMS_SUCCESS';
export const FETCH_COMPETITIONS_SUCCESS = 'FETCH_COMPETITIONS_SUCCESS';
export const FETCH_SEASONS_SUCCESS      = 'FETCH_SEASONS_SUCCESS';
export const FETCH_SEASON_SUCCESS       = 'FETCH_SEASON_SUCCESS';
